backend = "glx";
vsync = true;

# Reduce tearing
glx-copy-from-front = false;

# Performance tweaks
use-damage = true;

# Optional (nice visuals)
shadow = true;
fading = true;

fade-delta = 5;
fade-in-step = 0.08;
fade-out-step = 0.08;

animations = true;

animation-stiffness = 200.0;
animation-dampening = 20.0;
animation-clamping = false;

animation-for-open-window = "zoom";
animation-for-unmap-window = "fade";

shadow-exclude = [
  "class_g = 'Polybar'"
];
