#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -la'
alias n='nvim'
alias i='sudo pacman -S'
alias a='yay -S'
alias r='sudo pacman -Rcns'
alias ar='yay -Rns'
alias s='pacman -Ss'
alias as='yay -Ss'
alias au='yay -Syu'
alias u='sudo pacman -Syu'
alias cman='man 3'
alias b='cd ..'
alias ve="source .venv/bin/activate"
alias quick-note="todo quick-note"
alias check="todo check-note"
alias note="todo list-todo"
alias add-todo="todo add-todo"
alias view="kitty +kitten icat"
alias ga="git add -A"
alias gc="git commit -m"
alias push="git push origin main"
PS1='\u:\w\n> '

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

eval "$(fzf --bash)"

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

#f() {
#  local dir
#  dir=$(find ${1:-.} -path '*/.*' -prune -o -type d 2> /dev/null | fzf +m) && cd "$dir"
#}

f() {
  local dir
  dir=$(find "${1:-.}" -mindepth 1 \
    \( -path '*/.*' -o -maxdepth 4 \) \
    -type d -print 2> /dev/null | fzf +m) && cd "$dir"
}



bind '"\C-f": "\C-uf\C-m"'
bind -x '"\C-n": n'
bind -x '"\C-y": y'
bind -x '"\C-o": quick-note'
bind -x '"\C-e": note'
bind -x '"\C-g": check'
bind '"\ef":"jump\n"'
bind '"\er":"qj jump-files\n"'

export EDITOR=nvim
export MANPAGER='nvim +Man!'

export ZELLIJ_CONFIG_DIR="$HOME/.config/dotfiles/config/zellij"

if [[ -z "$ZELLIJ" ]]; then
    if command -v zellij >/dev/null 2>&1; then
      zellij --session "fresh-$(date +%s)"
    fi
fi

jump() {
    local DEST
    if [[ "$1" == "add" ]]; then
        qj add "$2" "${3:-.}"
        return
    fi
    DEST=$(qj jump-dirs "$@")
    if [[ $? -eq 0 && -n "$DEST" ]]; then
        cd "$DEST"
    else
        return 1
    fi
}

# pnpm
export PNPM_HOME="/home/saven/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
. "$HOME/.local/bin/env"
